apiVersion: v1
kind: PersistentVolume
metadata:
  name: eds-pv
  namespace: eds
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/ubuntu/elitedesignstudios.com  #location of code system in your machine
    type: DirectoryOrCreate