apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eds-pvc
  namespace: eds
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard