apiVersion: v1
kind: Service
metadata:
  name: elitedesignstudios-web
  namespace: elitedesignstudios
spec:
  selector:
    app: elitedesignstudios-web
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 80
      nodePort: 30007
  type: NodePort
