apiVersion: v1
kind: Service
metadata:
  name: elitedesignstudios-web
  namespace: eds
spec:
  selector:
    app: elitedesignstudios-web
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
